### ISSUE TITLE
Where is the Jar is it up do date

### ISSUE THREAD

**Issue by cmod31** [Loganh4005/SkinGate#1]
Hey i want to use this on my 1.17 Geyser Floodgate 2.0 offline-mode Server but i can't find a Jar File. Honestly i wouldn't know how to compile it and is it even up to date or working? I wan't to get rid of the Steve skins from the Bedrock players i hope this works

**Comment by Loganh4005** [comment]
uhhh.... I gave up on this. I couldn't find a way to get the png file. I may try soon. If you want to have bedrock skins, you can setup a MySQL and skin restorer, then get all the config files setup then you can tell the bedrock users you can use skin restorer

**Comment by cmod31** [comment]
They are implementing it to main skinrestorer there is already something but its buggy and you shouldn't use the plugin fastlogin with skin forwarding enabled like i did lol
